# Generated by Django 6.0.3 on 2026-04-05 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviezoneapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviezoneapp.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviezoneapp.customer')),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
